config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    get 'register', to: 'devise/registrations#new', as: :new_user_registration
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions], :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:index] do
    member do
      get '/give_kudo' => 'users#give_kudo'
    end

    collection do
      get '/profile' => 'users#profile'
      post '/profile' => 'users#update_profile'
    end
  end
  get '/top_ten_users' => 'users#top_ten'

  resources :teams, except: [:edit, :update, :destroy] do
    member do
      get '/add_member' => 'teams#add_member'
      get '/remove_member' => 'teams#remove_member'
    end
  end

  get 'landing_page/index'
  get 'terms_of_service' => 'terms_of_service#index'

  root 'landing_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kudo.rb
class Kudo < ApplicationRecord
  belongs_to :giver, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :users

  validates_presence_of :name, :description
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :teams
  has_many :given_kudos, class_name: 'Kudo', foreign_key: 'giver_id'
  has_many :received_kudos, class_name: 'Kudo', foreign_key: 'receiver_id'

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :name, :surname, :birth_date, unless: :skip_validation
  validates :terms_of_service, acceptance: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.skip_validation = true
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name.split[0]
      user.surname = auth.info.name.split[1]
      user.terms_of_service = true
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[birth_date terms_of_service name surname avatar avatar_cache remove_avatar])
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index; end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @sorted_users_list = @team.users.sort_by { |user| [user.received_kudos.count, -user.id] }.reverse
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to team_path(@team), notice: 'Created successfully'
    else
      render :new
    end
  end

  def add_member
    team = Team.find(params[:id])

    if current_user.teams.include?(team)
      redirect_to team, alert: 'You are already member of this team'
    else
      team.users << current_user
      redirect_to team, notice: 'You have become team member'
    end
  end

  def remove_member
    team = Team.find(params[:id])

    if current_user.teams.include?(team)
      team.users.delete(current_user)
      redirect_to team, notice: 'You are no longer a member of this team'
    else
      redirect_to team, alert: 'You are not a member of this team'
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :description)
  end
end

app/controllers/terms_of_service_controller.rb
class TermsOfServiceController < ApplicationController
  def index; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[index top_ten]

  def index
    sorted_users = User.all.sort_by { |user| [user.received_kudos.count] }.reverse
    @users = sorted_users.paginate(page: params[:page], per_page: 15)
  end

  def profile
    @user = current_user
  end

  def update_profile
    @user = current_user

    @user.skip_validation = false

    if @user.update(user_params)
      redirect_to root_path, notice: 'Data updated!'
    else
      render 'profile'
    end
  end

  def top_ten
    @users = User.all.sort_by { |user| [user.received_kudos.count] }.reverse.first(10)
  end

  def give_kudo
    user = User.find(params[:id])

    if (current_user.teams & user.teams).present? && current_user.id != user.id
      check_weekly_kudos_limit(user)
    else
      redirect_to request.referrer, alert: 'You are not team members'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :birth_date, :avatar, :weekly_kudos_limit)
  end

  def check_weekly_kudos_limit(user)
    if current_user.kudos_given_in_a_week < current_user.weekly_kudos_limit
      kudo_already_given?(user)
    else
      redirect_to request.referrer, alert: 'You have reached your weekly kudos limit'
    end
  end

  def kudo_already_given?(user)
    if current_user.given_kudos.pluck(:receiver_id).include?(user.id)
      redirect_to request.referrer, alert: 'You already gave a kudo to this user'
    else
      current_user.increment!(:kudos_given_in_a_week)
      Kudo.create(giver_id: current_user.id, receiver_id: user.id)
      redirect_to request.referrer, notice: 'You gave a kudo'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    classes = {
      notice: 'alert alert-info',
      success: 'alert alert-success',
      error: 'alert alert-error',
      alert: 'alert alert-error'
    }
    classes[level]
  end

  def custom_bootstrap_flash
    flash.map do |type, message|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      text.html_safe if message
    end.join("\n").html_safe
  end

  def current_class?(path)
    request.path == path ? 'active' : ''
  end

  def datepicker_input(form, field)
    content_tag :td, data: { :provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true' } do
      form.text_field field, class: 'form-control sign-up', placeholder: 'YYYY-MM-DD'
    end
  end
end

app/views/application/_flash_messages.html.erb
<% if flash.present? %>
  <!--  add in controller to use them: add_flash_types :success, :danger, :info-->
  <!--  example:     redirect_to some_path, type: 'text'-->
  <div id='flash'>
    <script>
        <% if flash[:success] %>
        var $toastContent = $('<span><%= flash[:success] %></span>');
        toastr.success($toastContent)
        <% end %>
        <% if flash[:info] %>
        var $toastContent = $('<span><%= flash[:info] %></span>');
        toastr.info($toastContent)
        <% end %>
        <% if flash[:danger] %>
        var $toastContent = $('<span><%= flash[:danger] %></span>');
        toastr.error($toastContent)
        <% end %>
    </script>
  </div>
<% end %>

app/views/landing_page/index.html.erb
<p>Hi this app allows you to give kudos to your teammates and search for new ones! Register today to gain full access</p>

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-primary', method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
  <%= link_to 'Register', new_user_registration_path, class: 'btn btn-info' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: 'shared/navbar' %>

  <title>Kudos</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= custom_bootstrap_flash %>
</head>

<body>
<div class="container">
  <div class="row text-center">
    <div class="col-md-8 col-md-offset-2">

      <%= render :partial => 'flash_messages', :flash => flash %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-default navbar-static-top'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <a class='navbar-brand'>Kudos App</a>
    </div>

    <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav'>
        <li><%= link_to 'Home', root_path, :class => current_class?(root_path) %></li>
        <li><%= link_to 'Teams', teams_path, :class => current_class?(teams_path) %> </li>
        <li><%= link_to 'Users', users_path, :class => current_class?(users_path) %> </li>
        <li><%= link_to 'Top 10 Users', top_ten_users_path, :class => current_class?(users_path) %> </li>
      </ul>

      <ul class='nav navbar-nav navbar-right'>
        <div class='collapse navbar-collapse'>
          <form class='navbar-form navbar-right display: flex align-items: center'>
            <%= render partial: 'shared/user_actions' %>
          </form>
        </div>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_actions.html.erb
<% if user_signed_in? %>
  <% value = (current_user.weekly_kudos_limit - current_user.kudos_given_in_a_week) %>
  <%= "Kudos left in this week: #{ (value > 0) ? value : 'none'}" %>
  <%= link_to 'Create team', new_team_path, class: 'btn btn-primary  float: right' %>
  <%= render partial: 'shared/user_dropdown' %>
<% else %>
  <% unless current_page?(root_path) %>
    <% unless current_page?(new_user_session_path) %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary' %>
    <% end %>
    <% unless current_page?(new_user_registration_path) %>
      <%= link_to 'Register', new_user_registration_path, class: 'btn btn-info' %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_user_dropdown.html.erb
<div style="display: inline-flex">
  <a class='dropdown-toggle float:right' data-toggle='dropdown'>
    <%= image_tag(current_user.avatar.thumb.url) %>
    <span class='caret'></span>
  </a>

  <!--User actions-->
  <ul class='dropdown-menu diplay:flex'>
    <li> <%= link_to 'Edit your data', profile_users_path(current_user) %> </li>
    <% if current_user.provider == nil %>
      <li class='divider'></li>
      <li> <%= link_to 'Change your password', edit_user_registration_path %> </li>
    <% end %>
    <li class='divider'></li>
    <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </li>
  </ul>
</div>

app/views/terms_of_service/index.erb
<h1>Terms of service</h1>
<%= link_to 'Back', url_for(:back) %>

app/views/users/edit.html.erb
<h3>Edit your data</h3>

<%= form_with scope: :user, local: true do |form| %>
  <% @user.errors.full_messages.each do |msg| %>
    <p class="bg-danger"><%= msg %></p>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :surname %><br>
    <%= form.text_field :surname %>
  </p>
  <div>
    <%= form.label 'Birth date' %><br/>
    <%= datepicker_input(form, :birth_date) %>
  </div>  <br>
  <p>
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table"
       data-pagination="true"
       data-page-size=5>
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Surname</th>
    <th class="text-center">Kudos Count</th>
  </tr>
  </thead>

  <tbody>
  <%= will_paginate @users %>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= image_tag(user.avatar.thumb_list.url) %>
        <%= user.name %>
      </td>
      <td><%= user.surname %></td>
      <td><%= user.received_kudos.count %></td>
      <% if user_signed_in? %>
        <% if (current_user.teams & user.teams).present? && current_user.id != user.id %>
          <td class="col-md-1 text-center"><%= link_to 'Give kudo', give_kudo_user_path(user), class: 'btn btn-default' %></td>
        <% else %>
          <td class="col-md-1 text-center"></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/profile.html.erb
<h3>Edit your data</h3>

<%= form_with scope: :user, local: true do |form| %>
  <% @user.errors.full_messages.each do |msg| %>
    <p class="bg-danger"><%= msg %></p>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :surname %><br>
    <%= form.text_field :surname %>
  </p>
  <div>
    <%= form.label :birth_date %><br/>
    <%= datepicker_input(form, :birth_date) %>
  </div>

  <p>
  <div class="field">
    <%= form.label :weekly_kudos_limit %><br/>
    <%= form.number_field :weekly_kudos_limit, min: 0 %>
  </div>
  </p>

  <p>
  <div class="field">
    <%= form.label :avatar %><br/>
    <%= form.file_field :avatar, class: 'upload-file' %>
  </div>
  </p>

  <p>
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/users/top10.html.erb
<h1>Top 10 Users</h1>

<table class="table"
       data-pagination="true"
       data-page-size=5>
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Description</th>
    <th class="text-center">Kudos Count</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.surname %></td>
      <td><%= user.received_kudos.count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/top_ten.html.erb
<h1>Top 10 Users</h1>

<table class="table"
       data-pagination="true"
       data-page-size=5>
  <thead>
  <tr>
    <th class="text-center">Name</th>
    <th class="text-center">Surname</th>
    <th class="text-center">Kudos Count</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= image_tag(user.avatar.thumb_list.url) %>
        <%= user.name %>
      </td>
      <td><%= user.surname %></td>
      <td><%= user.received_kudos.count %></td>
    </tr>
  <% end %>
  </tbody>
</table>